import { RestaurantInfo, MenuCategory } from './types';

export const RESTAURANT_INFO: RestaurantInfo = {
  name: 'The Fusion',
  address: '221 Lee High Rd, Blackheath, London SE13 5PQ',
  phone: '02045684224',
  email: 'info@fusionfood.co.uk',
  coordinates: {
    lat: 51.45880878334991,
    lng: 0.005527840859441247
  },
  openingHours: {
    monday: { open: '17:00', close: '23:00' },
    tuesday: { open: '17:00', close: '23:00' },
    wednesday: { open: '17:00', close: '23:00' },
    thursday: { open: '17:00', close: '23:00' },
    friday: { open: '17:00', close: '23:00' },
    saturday: { open: '12:00', close: '23:00' },
    sunday: { open: '12:00', close: '23:00' }
  }
};

// Complete menu data from menu.md
export const SAMPLE_MENU: { categories: MenuCategory[] } = {
  categories: [
    {
      id: 'appetizers',
      name: "Appetizers",
      description: "Traditional appetizers to begin your culinary journey",
      items: [
        {
          id: 'steamed-momo-lambchickenveg-dse',
          name: "Steamed Momo (Lamb/Chicken/Veg) (D/Se)",
          description: "Steamed dumplings served with tomato chutney.",
          price: 6.5,
          category: 'appetizers',
          options: ['Lamb', 'Chicken', 'Veg'],
        },
        {
          id: 'chilli-momo-lambchickenveg-dse',
          name: "Chilli MOMO (Lamb/Chicken/Veg) (D/Se)",
          description: "Stir-fried with peppers, fresh chilli, and aromatic spices.",
          price: 7.5,
          category: 'appetizers',
          options: ['Lamb', 'Chicken', 'Veg'],
        },
        {
          id: 'tandoori-momo-dse',
          name: "Tandoori MOMO (D/Se)",
          description: "Grilled dumplings filled with spiced minced chicken, served with tomato chutney.",
          price: 7.5,
          category: 'appetizers',
        },
        {
          id: 'sukuti-s',
          name: "Sukuti (S)",
          description: "Smoked and dried strips of lamb, sautéed with onion, garlic, ginger, and Nepali spices.",
          price: 8.5,
          category: 'appetizers',
        },
        {
          id: 'bhutan-s',
          name: "Bhutan (S)",
          description: "A traditional Nepali delicacy of goat tripe, stir-fried with onion, tomato, chilli, and spices.",
          price: 7.5,
          category: 'appetizers',
        },
        {
          id: 'chatpatey-g',
          name: "Chatpatey (G)",
          description: "Mix puffed rice, chopped onion, tomatoes, potato, chickpeas, and bombay mix, served cold.",
          price: 5.5,
          category: 'appetizers',
        },
        {
          id: 'onion-bhaji',
          name: "Onion Bhaji",
          description: "Crispy fried onion fritters.",
          price: 5.5,
          category: 'appetizers',
          isVegetarian: true,
        },
        {
          id: 'samosa-vegetablelambchicken-gd',
          name: "Samosa (Vegetable/Lamb/Chicken) (G/D)",
          description: "Crispy pastry with vegetable filling or minced lamb.",
          price: 5.5,
          category: 'appetizers',
          isVegetarian: true,
          options: ['Vegetable', 'Lamb', 'Chicken'],
        },
        {
          id: 'samosa-chaat-gd',
          name: "Samosa Chaat (G/D)",
          description: "Potato cakes with peas, yogurt, mint, and tamarind chutney.",
          price: 5.5,
          category: 'appetizers',
        },
        {
          id: 'pani-puri-g',
          name: "Pani Puri (G)",
          description: "Crispy puri filled with potatoes, onion, and tangy spiced water, served cold.",
          price: 5.5,
          category: 'appetizers',
        },
        {
          id: 'achari-paneer-tikka-d',
          name: "Achari Paneer Tikka (D)",
          description: "Char-grilled paneer slices marinated in spices.",
          price: 6.5,
          category: 'appetizers',
          isVegetarian: true,
        },
        {
          id: 'chilli-paneermushroomchicken-d',
          name: "Chilli (Paneer/Mushroom/Chicken) (D)",
          description: "Stir-fried with peppers, fresh chilli, and aromatic spices.",
          price: 6.5,
          category: 'appetizers',
          isVegetarian: true,
          options: ['Paneer', 'Mushroom', 'Chicken'],
        },
        {
          id: 'chicken-tikka-d',
          name: "Chicken Tikka (D)",
          description: "Chargrilled chicken breast cubes marinated in yogurt and herbs.",
          price: 5.5,
          category: 'appetizers',
        },
        {
          id: 'lamb-shish-kebab-d',
          name: "Lamb Shish Kebab (D)",
          description: "Minced lamb kebab cooked in the tandoor.",
          price: 5.5,
          category: 'appetizers',
        },
        {
          id: 'lamb-chops-d',
          name: "Lamb Chops (D)",
          description: "Juicy lamb chops marinated with traditional spices, grilled to perfection.",
          price: 9.5,
          category: 'appetizers',
        },
        {
          id: 'ajwani-salmon-d',
          name: "Ajwani Salmon (D)",
          description: "Salmon fillet marinated with carom seeds and fenugreek, grilled in clay oven.",
          price: 9.5,
          category: 'appetizers',
        },
        {
          id: 'prawn-puri-cd',
          name: "Prawn Puri (C/D)",
          description: "Spiced prawns served on deep-fried bread.",
          price: 7.5,
          category: 'appetizers',
        },
        {
          id: 'papadum',
          name: "Papadum",
          description: "Served with mint chutney.",
          price: 1.0,
          category: 'appetizers',
        },
        {
          id: 'pickle-or-chutney',
          name: "Pickle or Chutney",
          description: "Mint Chutney (D), Mango Chutney, Mixed Pickle or Onion Salad",
          price: 1.0,
          category: 'appetizers',
        },
      ]
    },
    {
      id: 'tandoori-grills',
      name: "Tandoori & Grills",
      description: "Clay oven grilled specialties",
      items: [
        {
          id: 'chicken-tikka-main-d',
          name: "Chicken Tikka Main (D)",
          description: "Chargrilled chicken breast cubes marinated in yogurt and herbs.",
          price: 10.5,
          category: 'tandoori-grills',
        },
        {
          id: 'chicken-tikka-shaslik-d',
          name: "Chicken Tikka Shaslik (D)",
          description: "Tender chicken skewers with peppers, tomato and onions.",
          price: 10.5,
          category: 'tandoori-grills',
        },
        {
          id: 'paneer-shaslik-d',
          name: "Paneer Shaslik (D)",
          description: "Paneer skewers with peppers, onions, and mild spices.",
          price: 10.5,
          category: 'tandoori-grills',
          isVegetarian: true,
        },
        {
          id: 'tandoori-chicken-d',
          name: "Tandoori Chicken (D)",
          description: "Half chicken marinated with yogurt and authentic spices, grilled in the tandoor.",
          price: 10.5,
          category: 'tandoori-grills',
        },
        {
          id: 'mixed-grill-platter-d',
          name: "Mixed Grill Platter (D)",
          description: "A mix of lamb kebab, chicken tikka, tandoori chicken, and lamb chop.",
          price: 12.5,
          category: 'tandoori-grills',
        },
        {
          id: 'lamb-chops-main-d',
          name: "Lamb Chops Main (D)",
          description: "Tender lamb chops marinated in Indian spices, served with chutney and salads.",
          price: 14.5,
          category: 'tandoori-grills',
        },
        {
          id: 'salmon-tikka-main-d',
          name: "Salmon Tikka Main (D)",
          description: "Chargrilled salmon with fenugreek and carom seed",
          price: 14.5,
          category: 'tandoori-grills',
        },
      ]
    },
    {
      id: 'chefs-recommendation',
      name: "Chef'S Recommendation",
      description: "Specially curated by our chef",
      items: [
        {
          id: 'himalayan-chicken-dm',
          name: "Himalayan Chicken (D/M)",
          description: "Chicken cooked with a rare Himalayan herb \"Zimbu\".",
          price: 12.5,
          category: 'chefs-recommendation',
        },
        {
          id: 'chicken-chilly-dry-fry-s',
          name: "Chicken Chilly Dry Fry (S)",
          description: "Crisp chicken stir-fried with peppers, chilli, and soy sauce.",
          price: 12.5,
          category: 'chefs-recommendation',
        },
        {
          id: 'lamb-bhutuwa',
          name: "Lamb Bhutuwa",
          description: "Tender lamb in tomato-onion gravy with fenugreek, garlic and spices.",
          price: 12.5,
          category: 'chefs-recommendation',
        },
        {
          id: 'sherpa-lamb',
          name: "Sherpa Lamb",
          description: "Tender lamb in tomato-onion gravy with complex roasted spices.",
          price: 12.5,
          category: 'chefs-recommendation',
        },
        {
          id: 'goan-prawn-dm',
          name: "Goan Prawn (D/M)",
          description: "Tiger prawns in coconut-based Goan sauce.",
          price: 13.5,
          category: 'chefs-recommendation',
        },
        {
          id: 'goan-tilapia-dm',
          name: "Goan Tilapia (D/M)",
          description: "Tilapia in coconut-based Goan sauce.",
          price: 13.5,
          category: 'chefs-recommendation',
        },
        {
          id: 'mix-seafood-curry-dmc',
          name: "Mix Seafood Curry (D/M/C)",
          description: "Tiger prawns, salmon, and tilapia in Goan sauce.",
          price: 13.5,
          category: 'chefs-recommendation',
        },
        {
          id: 'tawa-prawn-c',
          name: "Tawa Prawn (C)",
          description: "Tiger prawns sautéed with tomato, peppers, and spices.",
          price: 13.5,
          category: 'chefs-recommendation',
        },
        {
          id: 'karahi-paneer-d',
          name: "Karahi Paneer (D)",
          description: "Cottage cheese cooked with onion, tomato, and green peppers in a medium-spiced sauce.",
          price: 9.5,
          category: 'chefs-recommendation',
          isVegetarian: true,
        },
        {
          id: 'saag-chana-main',
          name: "Saag Chana Main",
          description: "Spinach & chickpeas cooked with garlic and spices.",
          price: 9.5,
          category: 'chefs-recommendation',
        },
      ]
    },
    {
      id: 'classic-curries',
      name: "Classic Curries",
      description: "Traditional curries available with your choice of protein",
      items: [
        {
          id: 'tikka-masala-dn-veg',
          name: "Tikka Masala (D/N) (Veg)",
          description: "Mild creamy tomato masala with ground almonds.",
          price: 8.5,
          category: 'classic-curries',
          isVegetarian: true,
        },
        {
          id: 'tikka-masala-dn-chicken',
          name: "Tikka Masala (D/N) (Chicken)",
          description: "Mild creamy tomato masala with ground almonds.",
          price: 10.5,
          category: 'classic-curries',
        },
        {
          id: 'tikka-masala-dn-lamb',
          name: "Tikka Masala (D/N) (Lamb)",
          description: "Mild creamy tomato masala with ground almonds.",
          price: 11.5,
          category: 'classic-curries',
        },
        {
          id: 'tikka-masala-dn-prawn',
          name: "Tikka Masala (D/N) (Prawn)",
          description: "Mild creamy tomato masala with ground almonds.",
          price: 12.5,
          category: 'classic-curries',
        },
        {
          id: 'kormadn-veg',
          name: "Korma(D/N) (Veg)",
          description: "Mild curry with coconut and almonds._ Dhansak",
          price: 8.5,
          category: 'classic-curries',
          isVegetarian: true,
        },
        {
          id: 'kormadn-chicken',
          name: "Korma(D/N) (Chicken)",
          description: "Mild curry with coconut and almonds._ Dhansak",
          price: 10.5,
          category: 'classic-curries',
        },
        {
          id: 'kormadn-lamb',
          name: "Korma(D/N) (Lamb)",
          description: "Mild curry with coconut and almonds._ Dhansak",
          price: 11.5,
          category: 'classic-curries',
        },
        {
          id: 'kormadn-prawn',
          name: "Korma(D/N) (Prawn)",
          description: "Mild curry with coconut and almonds._ Dhansak",
          price: 12.5,
          category: 'classic-curries',
        },
        {
          id: 'bhuna-veg',
          name: "Bhuna (Veg)",
          description: "Cooked in onion & tomato sauce with garlic, chilli, fresh herbs & spices.",
          price: 8.5,
          category: 'classic-curries',
          isVegetarian: true,
        },
        {
          id: 'bhuna-chicken',
          name: "Bhuna (Chicken)",
          description: "Cooked in onion & tomato sauce with garlic, chilli, fresh herbs & spices.",
          price: 10.5,
          category: 'classic-curries',
        },
        {
          id: 'bhuna-lamb',
          name: "Bhuna (Lamb)",
          description: "Cooked in onion & tomato sauce with garlic, chilli, fresh herbs & spices.",
          price: 11.5,
          category: 'classic-curries',
        },
        {
          id: 'bhuna-prawn',
          name: "Bhuna (Prawn)",
          description: "Cooked in onion & tomato sauce with garlic, chilli, fresh herbs & spices.",
          price: 12.5,
          category: 'classic-curries',
        },
        {
          id: 'karahi-veg',
          name: "Karahi (Veg)",
          description: "Onion and tomato-based curry with roasted spices.",
          price: 8.5,
          category: 'classic-curries',
          isVegetarian: true,
        },
        {
          id: 'karahi-chicken',
          name: "Karahi (Chicken)",
          description: "Onion and tomato-based curry with roasted spices.",
          price: 10.5,
          category: 'classic-curries',
        },
        {
          id: 'karahi-lamb',
          name: "Karahi (Lamb)",
          description: "Onion and tomato-based curry with roasted spices.",
          price: 11.5,
          category: 'classic-curries',
        },
        {
          id: 'karahi-prawn',
          name: "Karahi (Prawn)",
          description: "Onion and tomato-based curry with roasted spices.",
          price: 12.5,
          category: 'classic-curries',
        },
        {
          id: 'jalfrezi-veg',
          name: "Jalfrezi (Veg)",
          description: "Spicy curry with peppers and green chillies. Madras",
          price: 8.5,
          category: 'classic-curries',
          isVegetarian: true,
        },
        {
          id: 'jalfrezi-chicken',
          name: "Jalfrezi (Chicken)",
          description: "Spicy curry with peppers and green chillies. Madras",
          price: 10.5,
          category: 'classic-curries',
        },
        {
          id: 'jalfrezi-lamb',
          name: "Jalfrezi (Lamb)",
          description: "Spicy curry with peppers and green chillies. Madras",
          price: 11.5,
          category: 'classic-curries',
        },
        {
          id: 'jalfrezi-prawn',
          name: "Jalfrezi (Prawn)",
          description: "Spicy curry with peppers and green chillies. Madras",
          price: 12.5,
          category: 'classic-curries',
        },
      ]
    },
    {
      id: 'biryani',
      name: "Biryani",
      description: "Slow cooked with aromatic rice, spices, and caramelised onions, served with raita",
      items: [
        {
          id: 'veg-biryani-d',
          name: "Veg Biryani (D)",
          description: "",
          price: 10.5,
          category: 'biryani',
        },
        {
          id: 'chicken-biryani-d',
          name: "Chicken Biryani (D)",
          description: "",
          price: 11.5,
          category: 'biryani',
        },
        {
          id: 'lamb-biryani-d',
          name: "Lamb Biryani (D)",
          description: "",
          price: 12.5,
          category: 'biryani',
        },
        {
          id: 'prawn-biryani-dc',
          name: "Prawn Biryani (D/C)",
          description: "",
          price: 13.5,
          category: 'biryani',
        },
      ]
    },
    {
      id: 'vegetarian-dishes',
      name: "Vegetarian Dishes",
      description: "Vegetable dishes and sides",
      items: [
        {
          id: 'daal-makhani-d-main',
          name: "Daal Makhani (D) (Main)",
          description: "Slow-cooked black lentils in creamy sauce._ Paneer Makhani (D)",
          price: 8.5,
          category: 'vegetarian-dishes',
          isVegetarian: true,
        },
        {
          id: 'daal-makhani-d-side',
          name: "Daal Makhani (D) (Side)",
          description: "Slow-cooked black lentils in creamy sauce._ Paneer Makhani (D)",
          price: 5.5,
          category: 'vegetarian-dishes',
          isVegetarian: true,
        },
        {
          id: 'saag-aloo-d-main',
          name: "Saag Aloo (D) (Main)",
          description: "Spinach with potatoes.",
          price: 8.5,
          category: 'vegetarian-dishes',
          isVegetarian: true,
        },
        {
          id: 'saag-aloo-d-side',
          name: "Saag Aloo (D) (Side)",
          description: "Spinach with potatoes.",
          price: 5.5,
          category: 'vegetarian-dishes',
          isVegetarian: true,
        },
        {
          id: 'chana-masala-main',
          name: "Chana Masala (Main)",
          description: "Chickpeas in tomato-onion masala.",
          price: 8.5,
          category: 'vegetarian-dishes',
          isVegetarian: true,
        },
        {
          id: 'chana-masala-side',
          name: "Chana Masala (Side)",
          description: "Chickpeas in tomato-onion masala.",
          price: 5.5,
          category: 'vegetarian-dishes',
          isVegetarian: true,
        },
        {
          id: 'mushroom-masala-main',
          name: "Mushroom Masala (Main)",
          description: "Mushrooms with tomatoes, onions, and spices.",
          price: 8.5,
          category: 'vegetarian-dishes',
          isVegetarian: true,
        },
        {
          id: 'mushroom-masala-side',
          name: "Mushroom Masala (Side)",
          description: "Mushrooms with tomatoes, onions, and spices.",
          price: 5.5,
          category: 'vegetarian-dishes',
          isVegetarian: true,
        },
        {
          id: 'bombay-aloo-main',
          name: "Bombay Aloo (Main)",
          description: "Potatoes with herbs.",
          price: 8.5,
          category: 'vegetarian-dishes',
          isVegetarian: true,
        },
        {
          id: 'bombay-aloo-side',
          name: "Bombay Aloo (Side)",
          description: "Potatoes with herbs.",
          price: 5.5,
          category: 'vegetarian-dishes',
          isVegetarian: true,
        },
        {
          id: 'aloo-gobi-main',
          name: "Aloo Gobi (Main)",
          description: "Cauliflower and potatoes in spices.",
          price: 8.5,
          category: 'vegetarian-dishes',
          isVegetarian: true,
        },
        {
          id: 'aloo-gobi-side',
          name: "Aloo Gobi (Side)",
          description: "Cauliflower and potatoes in spices.",
          price: 5.5,
          category: 'vegetarian-dishes',
          isVegetarian: true,
        },
        {
          id: 'achari-aubergine-main',
          name: "Achari Aubergine (Main)",
          description: "Aubergine with tangy pickle spices.",
          price: 8.5,
          category: 'vegetarian-dishes',
          isVegetarian: true,
        },
        {
          id: 'achari-aubergine-side',
          name: "Achari Aubergine (Side)",
          description: "Aubergine with tangy pickle spices.",
          price: 5.5,
          category: 'vegetarian-dishes',
          isVegetarian: true,
        },
        {
          id: 'tadka-daal-main',
          name: "Tadka Daal (Main)",
          description: "Lentils tempered with garlic and cumin.",
          price: 8.5,
          category: 'vegetarian-dishes',
          isVegetarian: true,
        },
        {
          id: 'tadka-daal-side',
          name: "Tadka Daal (Side)",
          description: "Lentils tempered with garlic and cumin.",
          price: 5.5,
          category: 'vegetarian-dishes',
          isVegetarian: true,
        },
      ]
    },
    {
      id: 'rice-chowmein',
      name: "Rice & Chowmein",
      description: "Perfect sides",
      items: [
        {
          id: 'basmati-rice',
          name: "Basmati Rice",
          description: "",
          price: 2.95,
          category: 'rice-chowmein',
          isVegetarian: true,
        },
        {
          id: 'pilau-rice-d',
          name: "Pilau Rice (D)",
          description: "",
          price: 3.25,
          category: 'rice-chowmein',
          isVegetarian: true,
        },
        {
          id: 'hot-chilli-lemon-rice',
          name: "Hot Chilli Lemon Rice",
          description: "",
          price: 3.25,
          category: 'rice-chowmein',
          isVegetarian: true,
        },
        {
          id: 'mushroom-rice-d',
          name: "Mushroom Rice (D)",
          description: "",
          price: 3.5,
          category: 'rice-chowmein',
          isVegetarian: true,
        },
        {
          id: 'egg-rice',
          name: "Egg Rice",
          description: "",
          price: 3.5,
          category: 'rice-chowmein',
          isVegetarian: true,
        },
        {
          id: 'special-fried-rice',
          name: "Special Fried Rice",
          description: "",
          price: 3.95,
          category: 'rice-chowmein',
          isVegetarian: true,
        },
        {
          id: 'veg-chowmein-s',
          name: "Veg chowmein (S)",
          description: "",
          price: 7.5,
          category: 'rice-chowmein',
          isVegetarian: true,
        },
        {
          id: 'chicken-chowmein-s',
          name: "Chicken Chowmein (S)",
          description: "",
          price: 8.5,
          category: 'rice-chowmein',
        },
        {
          id: 'fusion-special-chowmein-cse',
          name: "Fusion Special Chowmein (C/S/E)",
          description: "Stir-fried egg noodles with tender chicken, shrimps, crisp vegetables and a rich, savory sauce",
          price: 9.5,
          category: 'rice-chowmein',
        },
      ]
    },
    {
      id: 'breads',
      name: "Breads",
      description: "Freshly baked traditional breads",
      items: [
        {
          id: 'plain-naand',
          name: "Plain Naan(D)",
          description: "",
          price: 2.95,
          category: 'breads',
        },
        {
          id: 'peshawari-naan-dn',
          name: "Peshawari Naan) (D/N)",
          description: "",
          price: 3.25,
          category: 'breads',
        },
        {
          id: 'garlic-naan-d',
          name: "Garlic Naan (D)",
          description: "",
          price: 3.25,
          category: 'breads',
        },
        {
          id: 'keema-naan-d',
          name: "Keema Naan (D)",
          description: "",
          price: 3.25,
          category: 'breads',
        },
        {
          id: 'chapati',
          name: "Chapati",
          description: "",
          price: 2.95,
          category: 'breads',
        },
        {
          id: 'tandoori-roti',
          name: "Tandoori Roti",
          description: "",
          price: 2.95,
          category: 'breads',
        },
        {
          id: 'aloo-paratha',
          name: "Aloo Paratha",
          description: "",
          price: 3.5,
          category: 'breads',
        },
        {
          id: 'lachha-paratha',
          name: "Lachha Paratha",
          description: "",
          price: 3.5,
          category: 'breads',
        },
      ]
    },
    {
      id: 'accompaniments',
      name: "Accompaniments",
      description: "Perfect sides to complement your meal",
      items: [
        {
          id: 'kachumber-salad',
          name: "Kachumber Salad",
          description: "",
          price: 3.95,
          category: 'accompaniments',
        },
        {
          id: 'mix-green-salad',
          name: "Mix Green Salad",
          description: "",
          price: 3.95,
          category: 'accompaniments',
        },
        {
          id: 'raita-d',
          name: "Raita (D)",
          description: "",
          price: 3.95,
          category: 'accompaniments',
        },
      ]
    },
    {
      id: 'drinks',
      name: "Drinks",
      description: "Refreshing beverages",
      items: [
        {
          id: 'can-cokediet-cokelemonade-330ml',
          name: "Can Coke/Diet Coke/Lemonade (330ml)",
          description: "",
          price: 2.5,
          category: 'drinks',
          options: ['Coke', 'Diet Coke', 'Lemonade']
        },
        {
          id: 'bottle-cokediet-cokelemonade-125l',
          name: "Bottle Coke/Diet Coke/Lemonade (1.25l)",
          description: "",
          price: 3.5,
          category: 'drinks',
          options: ['Coke', 'Diet Coke', 'Lemonade']
        },
        {
          id: 'still-sparkling-water-750ml',
          name: "Still /Sparkling Water (750ml)",
          description: "",
          price: 3.5,
          category: 'drinks',
          options: ['Still', 'Sparkling']
        },
        {
          id: 'stillsparkling-water-330ml',
          name: "Still/Sparkling Water (330ml)",
          description: "",
          price: 2.5,
          category: 'drinks',
          options: ['Still', 'Sparkling']
        },
      ]
    },
  ]
};

export const NAVIGATION_ITEMS = [
  { name: 'Home', href: '/' },
  { name: 'Menu', href: '/menu' },
  { name: 'Reservations', href: '/reservations' },
  { name: 'Order Online', href: '/order' },
  { name: 'Contact', href: '/contact' },
];
